
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    
  app:
    build: ./chat-app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: messagesDB 
    volumes:
      - 'chatappdata:/vat/lib/mysql'
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="password"']
      interval: 3s
      retries: 5
      start_period: 30s

volumes:
  chatappdata: